### ISSUE TITLE
Where is the webapps test script gone?

### ISSUE THREAD

**Issue by nicola** [harthur/firefox-client#6]
Hello there,
I was looking fot the webapps example but I think it is expired on pastebin.

> [webapps test script](https://pastebin.mozilla.org/5094843) - a sample usage of all webapps features

can you re-upload that?

Cheers!

**Comment by sole** [comment]
Hah, I was going to file this very same issue :)

**Comment by nicola** [comment]
@sole, I implemented a very similar thing to deploy to FirefoxOS in here: https://github.com/nicolagreco/fireplay-js/blob/master/lib/fireplay.js
